### ISSUE TITLE
Removed Desert Feathers

### ISSUE THREAD

**Issue by YetiHug** [SoaringGecko/calamityVanillaItemRecipeChanges1.4#1]
Desert Feathers were removed from calamity in the most recent update. Calamity mod wiki reflects this: '[https://calamitymod.wiki.gg/wiki/Desert_Feather](url)' This affects the 'Flying Carpet' and 'Sandstorm in a Bottle' recipes.

**Comment by SoaringGecko** [comment]
The new recipes kind of suck and make no sense, so this will most likely not be changed, we shall see.

As I am unsure as to if I want to change this or not, I will keep this issue open for now.

**Comment by SoaringGecko** [comment]
I have changed my mind, I will be changing this, thank you for letting me know about this change.

**Comment by SoaringGecko** [comment]
After thinking on this for longer, I shall not be changing this as removing the Desert Feather just to introducing the Pearl Shard makes no sense what so ever.
